image: Visual Studio 2017

# Prevent the double build when a branch has an active PR
skip_branch_with_pr: true

# Update any submodules we add
before_build:
  - git submodule -q update --init

build_script:
- cmd: build.cmd